GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "Nama": "Rumah Sakit Oetomo",
    "Jenis": "RSUS",
    "Kelas": "B",
    "Kapasitas": "10000",
    "Alamat": "Jalan Buah Batu",
    "Telepon":"081234567"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "Nama": "Rumah Sakit Al-ihsan",
    "Jenis": "RSUD",
    "Kelas": "A",
    "Kapasitas": "10000",
    "Alamat": "Jalan Bale Endah",
    "Telepon":"089876543"
}

###
DELETE http://localhost:5000/users/


###
GET http:/localhost:5000/users?search_query=oetomo&page=0&limit=10